### ISSUE TITLE
totally not a big issue, but perhaps something that could help?

### ISSUE THREAD

**Issue by devonorourke** [nextgenusfs/amptk#21]
Hi Jon,

A recent batch of samples consisted of several .fq files which contained zero bytes of data along with lots of good reads for other samples. If I run all of these files (including those with zero bytes of information) through the 'amptk illumina' command the run crashes on the first file with zero bytes with the following message:

Traceback (most recent call last):
  File "/home/fosterLab/devonr/bin/ufits-v0.7.2/bin/ufits-process_illumina_folder.py", line 293, in <module>
    MergeReads(for_reads, rev_reads, name, read_length)
  File "/home/fosterLab/devonr/bin/ufits-v0.7.2/bin/ufits-process_illumina_folder.py", line 74, in MergeReads
    pct_out = finalcount / float(origcount)
ZeroDivisionError: float division by zero

If I manually remove these files ahead of time the error is avoided. I was just curious if there would be a way for amptk to simply ignore files that don't contain any information. No big deal, but thought I'd let you know about this peculiar instance (for folks like me that are parsing hundreds of samples at once, there's a chance you simply miss the observation that a sample or two that didn't generate any sequence data).

Cheers,

Devon

**Comment by nextgenusfs** [comment]
I think this should fix that: https://github.com/nextgenusfs/amptk/commit/0b159f4f40cf6b1191689f071d12a90e8a9dce8e

**Comment by nextgenusfs** [comment]
Supported in v0.8.6
