### ISSUE TITLE
Results naming for DADA2 and UNOISE2

### ISSUE THREAD

**Issue by vmikk** [nextgenusfs/amptk#22]
Hello Jon!
First of all, thanks for the great software!

I have tested DADA2 pipeline with `amptk` and tried to compare it with UNOISE2 pipeline.
After taxonomic annotation I found "No Hit" in the resulting OTU table from the DADA pipeline.
Then I realized that this is because of a different naming scheme of the results:

DADA2 (`amptk dada2 ...`)
test.**otu_table.txt** - table with iSeqs 
test.cluster.otu_table.txt - table with OTUs (clustered iSeqs)

UNOISE2 (`amptk unoise2 ...`)
test.iSeq.otu_table.txt - table with iSeqs 
test.**otu_table.txt** - table with OTUs (clustered iSeqs)

Maybe it's better to make filenames for the results of DADA pipeline consistent with UNOISE2 pipeline?
I mean that `test.otu_table.txt` (which is expected as `-i` argument in `amptk taxonomy`) should correspond to OTUs for both methods.

With best regards,
Vladimir

**Comment by nextgenusfs** [comment]
Thanks Vladimir.  I will make the naming conventions the same. The iSeq name annotation should also work in the taxonomy stage as well so will look into why it does not.

**Comment by nextgenusfs** [comment]
Hi Vladimir, I just pushed an update to fix this https://github.com/nextgenusfs/amptk/commit/1506dc47d89456ac0bb706915ebd3d86c18793c3.  I also double checked taxonomy is working for both iSeqs and clustered iSeqs.  If you are getting 'No hit' still let me know, but if you are it is actually saying there was no taxonomy hit, which could mean that taxonomy prediction has failed or the database that you used was wrong.  Let me know if v0.8.8 is now working as you would expect.

**Comment by vmikk** [comment]
Thank you very much for your reply and a fast fix.
I’m sorry, I should be more specific with “No Hit”.
Last time after UNOISE2 and DADA2 clustering I launched taxonomic classification with:
```
amptk taxonomy -f unoise.cluster.otus.fa -i unoise.cluster.otu_table.txt …
amptk taxonomy -f dada.cluster.otus.fa -i dada.cluster.otu_table.txt …
```
Resulting unoise.otu_table.taxonomy.txt was fine (OTUs + their annotation). But in dada.otu_table.taxonomy.txt all taxa had “No Hit”. It’s obvious, because names in dada.cluster.otu_table.txt (iSeq\_\*) are different from sequences in fasta file (OTU\*). So the database was just wrong.

Now, with consistent names after your fix, everything is perfect. Thanks!
