### ISSUE TITLE
edlib - invalid ELF header

### ISSUE THREAD

**Issue by vmikk** [nextgenusfs/amptk#25]
Hello Jon!
I tried to update AMPtk to the most recent version (v0.10.2) and received the following error:
```
ImportError: /home/mik/amptk/lib/edlib.so: invalid ELF header
```
OS - Linux Mint (Ubuntu-based)
edlib v.1.2.0 is installed via pip (`pip install -U edlib`)

Could you please tell me how to resolve this problem?

**Comment by nextgenusfs** [comment]
Oh, that file should be there.... I think the ELF is an error complaining about the .so file in the lib directory.  try to remove that file, i.e. `rm /home/mik/amptk/lib/edlib.so`.  I was trying to have edlib build during install locally, but haven't gotten it to work smoothly yet, and best way to install right now is via pip as you did.

**Comment by vmikk** [comment]
Thanks for the reply!  Removal of `amptk/lib/edlib.so` helped and `amptk` is working now.

**Comment by nextgenusfs** [comment]
amptk now requires edlib v1.2.1 -> there was a bug in previous versions of the library.  edlib locally has been removed from repository
