### ISSUE TITLE
Hybrid taxonomy abbreviations

### ISSUE THREAD

**Issue by vmikk** [nextgenusfs/amptk#27]
Hello Jon!
This is not really an issue, but a question.

After taxonomy assignment with hybrid approach (USEARCH, SINTAX, UTAX) using `amptk` < v.0.9.0 resulting taxonomy is self-explanatory and looks like:
```
ID;k:Fungi,…         # where ID is an accession number of the best hit.
UTAX;k:Fungi,…
SINTAX;k:Fungi,…
```
In `amptk` >= v.0.9.0 resulting taxonomy looks like "`XX|PercentIdentiy|ID;k:Fungi…`", where XX can be GD, GS, SS, US. Unfortunately, I cannot find description of these abbreviations in the documentation. If I understand correctly:
-	GS means taxonomy based on global alignment hits (USEARCH)
-	SS means SINTAX-based taxonomy
-	US means UTAX-based taxonomy

But what does GD mean? Is it used when the methods gives controversial results and resulting taxonomy is LCA-based?

**Comment by nextgenusfs** [comment]
Yes that's exactly correct, D standing for discrepancy and then output is LCA. Sorry not fully documented, need to spend some time on the wiki.

**Comment by vmikk** [comment]
Thank you for the answer! It's clear now.
I think we can close this issue.
