### ISSUE TITLE
amptk filter - structure of otutable.demux.fq for new OTU table

### ISSUE THREAD

**Issue by jack1120** [nextgenusfs/amptk#29]
Hi Jon,

I would like to use `amptk filter` to generate a 'cleaned' OTU table on an existing OTU table that I made using a different pipeline. I can use the `amptk filter` command fine, but then need to make a new OTU table with the normalized and cleaned output using `amptk remove` and subsequently `vsearch --usearch_global`. 

This requires that I have a ".demux.fq" file that would normally be generated in earlier steps of the amptk pipeline. The sequences that I got back from the sequencing center are not yet demultiplexed at the sample level due to the way that we prepared our constructs, and can not be plugged directly into the amptk pipeline. I am hoping that I can generate a ".demux.fq" file independently from intermediate files in my pipeline, but need to know what this file consists of. Can I just concatenate sample-level fastq files that have been quality filtered and trimmed to generate this?

Thanks,
Lauren

**Comment by nextgenusfs** [comment]
What format is your data in now?  Probably the most important data analysis is actually the pre-processing of reads, so I would caution against doing primer stripping and quality filtering with other methods.  The pre-processing scripts are fairly versatile and might work with the way you have your raw data.  And I'm willing to add another method if it is a commonly used format. 

You can generate a compatible OTU table with `vsearch`, the FASTQ headers need to contain which sampleID the read originated from.  AMPtk uses `;barcodelabel=sample;` format.

**Comment by jack1120** [comment]
My samples were prepared (MiSeq, PE, 2x250bp) with unique combinations of tags on the 5' end of both the forward (gITS7) and reverse (ITS4) primers. These samples were split into pools and illumina indices were ligated onto the constructs (TruSeq PCR-Free LT Library Prep Kit), with a different set of indices used for each pool. The final construct looks like:

`P5-Index1-For_Tag:For_Primer-Amplicon-Rev_Primer:Rev_Tag-Index2-P7`

The sequencing center demultiplexed the sequences by the indices such that I received files for each of my pooled samples that, after merging, would theoretically look like:

`For_Tag1:For_Primer-Amplicon-Rev_Primer:Rev_Tag1`
`For_Tag2:For_Primer-Amplicon-Rev_Primer:Rev_Tag2`
`For_Tag3:For_Primer-Amplicon-Rev-Primer:Rev_Tag3`
`etc.`

Where each unique tag combination represents amplicons from a given sample (but all in a single fastq file). Although these are Illumina sequences, the structure is more similar to what you describe for processing Ion Torrent or 454 data, but with an additional tag attached to the reverse primer.

I am currently demultiplexing the R1 (using the For_Tags) and R2 (using the Rev_Tags) files independently, looking in both the 5'-3' and 3'-5' orientations (how does amptk handle mixed orientations?). The tags and primers are then trimmed, and the sequences are fed into DADA2 where they are quality filtered, merged, and denoised. The resulting OTU tables are then re-formatted into a vsearch-compatible format for further processing.
