### ISSUE TITLE
tiny request on database/taxonomy install

### ISSUE THREAD

**Issue by devonorourke** [nextgenusfs/amptk#32]
It would be great to know when the database was last updated. You mention when the ITS database was last updated in [the docs](http://amptk.readthedocs.io/en/latest/taxonomy.html), but no other db have any specific info.  

Would it be possible to run something like `amptk taxonomy`, and then at the bottom where we see a list of `Databases Configured:`, include another column with the last update?

Gotta keep you busy Jon...

**Comment by nextgenusfs** [comment]
Yeah, easier said then done, but been meaning to do something along these lines.  FYI CO1 was updated in v1.0.0 https://github.com/nextgenusfs/amptk/releases/tag/1.0.0

**Comment by nextgenusfs** [comment]
And the Database download files are here https://osf.io/4xd9r/files/ in case you are interested.

**Comment by nextgenusfs** [comment]
`v1.4.0` expands on this a little and has database version numbers in the `amptk info` command.
