### ISSUE TITLE
a little quirk (bug?) due to formatting in `biom convert`

### ISSUE THREAD

**Issue by devonorourke** [nextgenusfs/amptk#43]
Sometimes I have use for `.csv` formats, others `.tsv`. Often when I'm working in AMPTK I use `.csv` formats because I find it easier to filter some things manually. 
What I noticed is that if you set the output to `.csv` format in the `amptk filter` step, then run `amptk taxonomy` with that `.csv` file, you don't generate a `.biom` file.
It fails, apparently, because the `biom convert` argument doesn't recognize a comma-separated file! I converted it to a tab-delimited file and it worked just fine.

**Comment by devonorourke** [comment]
First, please ignore if this was already fixed. I'm using `amptk v1.1.4`, so not the most up to date...

I wanted to add that in the next step, after the `*.biom.tmp` file is created and you append the metadata... In my system the default file name it was looking for to find the taxonomy table wasn't right:
The script looked for:
```
 biom add-metadata -i Mangan.biom.tmp -o Mangan.biom --observation-metadata-fp Mangan.qiime.taxonomy.txt -m mangan.mappingFile.txt --sc-separated taxonomy --output-as-json
```

But there isn't any `Mangan.qiime.taxonomy.txt` file. Instead, the default name is `Mangan.otu_table.taxonomy.txt`. Once I swapped that manually it worked fine.

Cheers!

**Comment by nextgenusfs** [comment]
Looks like `amptk taxonomy` is expecting only tab delimited.  So I guess I never saw this because I don't ever use csv -- I only added that as a request from Michelle.  https://github.com/nextgenusfs/amptk/blob/17fc498b429a9e489e7b2b8b6b99e339be0113f9/bin/amptk-assign_taxonomy.py#L196

**Comment by devonorourke** [comment]
Michelle is such a trouble maker...
Easy fix anyhow. Thanks.
