### ISSUE TITLE
16s Illumina

### ISSUE THREAD

**Issue by FilipeMatteoli** [nextgenusfs/amptk#46]
Hello Mr. Palmer,
I have used amptk to process ITS fungal sequences with great success, however now I am trying to use it on bacterial v3-v4 16S data. I could not find in the documentation how to properly run the illumina command, doc contains:
#simple folder of PE MiSeq data
"amptk illumina -i miseq_folder/ -o mydata -f ITS1-F -r ITS2"
I cannot figure how to properly tell amptk which primers i have used. Does this command check for an indexed primer sequence db ? 

Thanks in advance.

**Comment by nextgenusfs** [comment]
The amptk primers command will tell you which sequences there are shortcuts for, if you used different primers then you just need to enter the primer sequence that you want trimmed into the forward -f and reverse -r options. Be careful of how the amplicons were sequenced, some setups use non-illumina sequencing primers and therefore the data won’t have the primers. Basically you enter what sequence you want the software to trim from the forward and reverse part of the amplicon.

**Comment by FilipeMatteoli** [comment]
Understood if my data has no primers how do I set these parameters to null? I tried using 0 and received:
ValueError: invalid literal for int() with base 10: 'post1' 

Thanks for your time once again.

**Comment by nextgenusfs** [comment]
Look at the help menu for each command, it is the —require_primer option you set to false. It will still look for primers that you specify but won’t discard read if they aren’t found. So still use the primer sequences you used to construct library.

**Comment by FilipeMatteoli** [comment]
Still could not manage to run, I always get this output with or without --require_primer, here's my command:

amptk illumina -i '/media/filipe/rema_seq_vogel/raw_data/e10/' --out amptk_pipeline -f CCTACGGGCGGCGGCAG -r GACTACATGGGTATCTAATCC --require_primer off --cpus 2

Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/amptk/opt/amptk-1.2.4/bin/amptk-process_illumina_folder.py", line 203, in <module>
    amptklib.SystemInfo()
  File "/home/filipe/miniconda3/envs/amptk/opt/amptk-1.2.4/lib/amptklib.py", line 210, in SystemInfo
    mod_versions()
  File "/home/filipe/miniconda3/envs/amptk/opt/amptk-1.2.4/lib/amptklib.py", line 225, in mod_versions
    if not gvc(vers, '1.2.1'):
  File "/home/filipe/miniconda3/envs/amptk/opt/amptk-1.2.4/lib/amptklib.py", line 134, in gvc
    if versiontuple(input) >= versiontuple(check):
  File "/home/filipe/miniconda3/envs/amptk/opt/amptk-1.2.4/lib/amptklib.py", line 131, in versiontuple
    return tuple(map(int, (v.split("."))))
ValueError: invalid literal for int() with base 10: 'post1'

Maybe I am having some install issue? I tried deleting and reinstalling miniconda3 and ended up with the same results. Also, I followed all steps, usearch 9.2.64 is softlinked i am using i86linux32 version, my system is Ubuntu 18.04.

Curiously i've ran this successfully in the past as follows: 
amptk illumina -i '/home/filipe/Documents/colab1/raw_reads' -o grape --require_primer off --cpus 2

Thanks once again.

**Comment by nextgenusfs** [comment]
This is related to edlib install. Try to reinstall python-edlib with conda. This is fixed in v1.2.5.

**Comment by nextgenusfs** [comment]
There is a new version on bioconda, hopefully this problem is solved.  In the next few days I'll have some maintenance updates.

**Comment by nextgenusfs** [comment]
`v1.4.0` was released on pip, can you give that a try?  `pip install amptk`.  Note this will not install the external non-python dependencies.

**Comment by FilipeMatteoli** [comment]
Sorry for not getting back sooner. Installing edlib fixed it, I will try v.1.4.0.
