### ISSUE TITLE
amptk summarize

### ISSUE THREAD

**Issue by mjusino** [nextgenusfs/amptk#48]
amptk summarize appears to have a bug, the output files show that each sample is even across all OTUs at all taxonomic levels - this is not reflected in the input OTU table. 
I was made aware of this by a different user, then tested on multiple OTU tables including theirs and my results are consistent. I tried using --percent and had the same issue.

**Comment by nextgenusfs** [comment]
Okay, not sure when this stopped working, perhaps awhile ago when py2/3 compatibility.  I just re-wrote the script.  Let me know if there are any other issues, I have updates to taxonomy databases which seem to help substantially with ITS (less sure about the others). But had to change the architecture of the taxonomy search to use vsearch for all global alignments as ITS taxonomy database has gotten too large to work with the 32 bit version of usearch. https://github.com/nextgenusfs/amptk/commit/034804f27a03da36f9290ad463d4d3aab1a4b736

**Comment by nextgenusfs** [comment]
Should be fixed in `v1.4.0`, re-open if still having problems.
