### ISSUE TITLE
Does the 'amptk filter' remove non-representative OTUs ?

### ISSUE THREAD

**Issue by bsmoda** [nextgenusfs/amptk#50]
Hi Jon,

The --min_reads_otu parameter of 'amptk filter' excludes OTUs within samples with frequency below of delimited? I've run the 'amptk filter' with the default parameter, but in my OTU table still are present OTUs with frequency of 1.

**Comment by nextgenusfs** [comment]
Did some samples get dropped?  I think it looks at the raw counts prior to any manipulation of the OTU table.

**Comment by bsmoda** [comment]
No samples get dropped, but the input of 'amptk filter' are the otu table and the otu fasta file generated from 'amptk cluster'. I thought that the filter command would drop otus (from otu_table) which didn't pass the number of --min_reads_otu parameter.

**Comment by nextgenusfs** [comment]
The filter is done by summing each row (OTU) and dropping those that are less than the --min_reads_otu parameter.  This is done prior to any other filtering, i.e. if a mock community is used for filtering these calculations are done before any of the mock-related filtering is done. Do you have a small test case you can show me that isn't working?
