### ISSUE TITLE
AMPtk filter not finding usearch

### ISSUE THREAD

**Issue by rmsegnitz** [nextgenusfs/amptk#51]
Hi there, 
I have just gotten AMPtk and its dependencies installed, but it seems not to be finding usearch9 when calling the filter function. 

Trying to run the filter command returns the error:

> usearch9 not found in your PATH, exiting.

I have installed USEARCH manually and created a soft link as specified. 

I verified that "usearch9" exists in my  "/usr/local/bin" directory, and that it links correctly to the actual "usearch9.2.64_i86osx32" file.

Any suggestions on where things might be misspecified and how I can sort this out?

Thanks so much in advance!
Max

**Comment by nextgenusfs** [comment]
When you type usearch9 you get the version displayed on command line?

**Comment by rmsegnitz** [comment]
No, I don't. 
It returns:
usearch9: command not found

I think the link directs, but maybe doesn't execute the file?

**Comment by nextgenusfs** [comment]
It is not in the $PATH then. You should be able to type which usearch9 and it will show you the path to the file.  Steps are to make sure original binary is executable, i.e. you ran 
```chmod +x /full/path/to/usearch9.2.64_i86osx32```
Verify that it works, via running 
```/full/path/to/usearch9.2.64_i86osx32```
Then setup your softlink into a directory in your $PATH, i.e. 
```ln -s /full/path/to/usearch9.2.64_i86osx32 /usr/local/bin/usearch9```

Note you can't overwrite a softlink, so if you made one that is incorrect and points to nothing, you will have to delete it before making the new one.

**Comment by rmsegnitz** [comment]
Thanks so much, that cleared things up.

I think that I had originally misspecified something when making the binary executable, and then since the softlinks cannot be overwritten  my attempts to correct were not carried through. 

Deleting and redesignating the softlink after making sure the binary was executable fixed everything.
