### ISSUE TITLE
Does ion preprocessing filters only reads that contains both forward and reverse primers?

### ISSUE THREAD

**Issue by bsmoda** [nextgenusfs/amptk#52]
Hello @nextgenusfs,

I would like to know if the preprocessing step of amptk filters only reads with both f and r primers, because the ITS region (in my case ITS2) have variable length, and the limit of the reads length of the sequencing was of 400 bp. Thus, if this step filters only reads with both primers I could be losing reads longer than 400 bp that contains only one of the primers.

**Comment by nextgenusfs** [comment]
For ion preprocessing the forward primer is required, along with a valid barcode sequence. The reverse primer is removed if it is found.  https://amptk.readthedocs.io/en/latest/pre-processing.html

**Comment by bsmoda** [comment]
If not found, the read is maintained or is dropped from the processing?

**Comment by nextgenusfs** [comment]
Reads without valid barcodes or forward primers are discarded in the ion workflow.  Not sure what isn’t clear in the docs?

**Comment by bsmoda** [comment]
I think is clear now. I didn't understand that only forward primer is necessary for the processing. I thought that only the read would pass the processing if both primers forward and reverse were present in the read.
That helps a lot, thank you Jon!
