### ISSUE TITLE
UnboundLocalError: local variable 'hit' referenced before assignment

### ISSUE THREAD

**Issue by atiweb** [nextgenusfs/amptk#55]
OS: debian buster/sid, 8 cores, ~ 16 GB RAM. Python: 3.7.3
 AMPtk v1.4.0, USEARCH v10.0.240, VSEARCH v2.13.4
Loading FASTA Records
 8,203 OTUs
Global alignment OTUs with usearch_global (VSEARCH) against ITS.udb
 Classifying OTUs with UTAX (USEARCH)
Classifying OTUs with SINTAX (USEARCH)
 UTAX results empty
 SINTAX results empty
Traceback (most recent call last):
  File "/amptk/bin/amptk", line 735, in <module>
    main()
  File "/amptk/bin/amptk", line 726, in main
    mod.main(arguments)
  File "/amptk/lib/python3.7/site-packages/amptk/assign_taxonomy.py", line 320, in main
    bestClassify = amptklib.bestclassifier(utaxDict, sintaxDict, otuList)
  File "/amptk/lib/python3.7/site-packages/amptk/amptklib.py", line 1494, in bestclassifier
    BestClassify[otu] = hit
UnboundLocalError: local variable 'hit' referenced before assignment

running:
amptk taxonomy -f .cluster.filtered.otus.fa -i .cluster.final.txt -m mapping_file.txt -d ITS2 -u usearch10

**Comment by nextgenusfs** [comment]
You need usearch9.

**Comment by atiweb** [comment]
Thanks. We tried it later with usearch9 and it works beatifully
