### ISSUE TITLE
UnboundLocalError: local variable 'hit' referenced before assignment when using '--fasta_db'

### ISSUE THREAD

**Issue by Alenap26** [nextgenusfs/amptk#58]
Hi,
I'm trying to use my personal db:
amptk taxonomy -f miseq.lulu.otus.fa -i miseq.lulu.otu_table.txt -m miseq.mapping_file.txt --fasta_db silva18S.fa -o miseq

I also tried (like: https://github.com/nextgenusfs/amptk/issues/55 ): 
amptk taxonomy -f miseq.lulu.otus.fa -i miseq.lulu.otu_table.txt -m miseq.mapping_file.txt --fasta_db db_18S/silva18S.fa -o miseq -u usearch9

but I have the same error:
`
Traceback (most recent call last):
  File "/Users/Alessandro/anaconda3/bin/amptk", line 735, in <module>
    main()
  File "/Users/Alessandro/anaconda3/bin/amptk", line 726, in main
    mod.main(arguments)
  File "/Users/Alessandro/anaconda3/lib/python3.7/site-packages/amptk/assign_taxonomy.py", line 320, in main
    bestClassify = amptklib.bestclassifier(utaxDict, sintaxDict, otuList)
  File "/Users/Alessandro/anaconda3/lib/python3.7/site-packages/amptk/amptklib.py", line 1494, in bestclassifier
    BestClassify[otu] = hit
UnboundLocalError: local variable 'hit' referenced before assignment
'

**Comment by Alenap26** [comment]
I'm looking for to use db SILVA 18S, I saw that's an open issue : https://github.com/nextgenusfs/amptk/issues/44
Is not possibile to use the db in fasta format as I have tried ?

**Comment by nextgenusfs** [comment]
If you use only the global alignment search it should be okay (any fasta should work), ie —method usearch.

**Comment by Alenap26** [comment]
Ok thanks
