### ISSUE TITLE
generate fasta files from udb after database install

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/amptk#59]
Note to remind @nextgenusfs or @hyphaltip to add code after `amptk setup` to run udb2fasta on the database files so that they are built at same time (eg ITS.extracted.fa 16S.extracted.fa) so to generate these fasta files during the setup stage not rely on it to be generated during first run of taxonomy since the permissions of the setup user installing in system folders could be different from the user running amptk.

**Comment by nextgenusfs** [comment]
fixed in v1.4.1
