### ISSUE TITLE
dada2 pipeline error

### ISSUE THREAD

**Issue by bsmoda** [nextgenusfs/amptk#63]
Hi there @nextgenusfs,
I was trying to run the dada2 analysis for the Ion PGM data from the AMPTk paper, but I got this error:
```
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/mnt/data2/lbcb/conda/envs/amptk3/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.64: cannot open shared object file: No such file or directory
Execution halted
``` 
I don't understand this error.
It also takes too long for splitting the FASTQ records, is this normal?
I'm using Python: 3.6.8; AMPtk v1.4.0; USEARCH v9.2.64; VSEARCH v2.10.4; R v3.6.1 and DADA2 v1.12.1

Thanks for your support!

**Comment by bsmoda** [comment]
Hello again

I was able to fix the error by creating a new amptk env within conda like the following:
```
conda create -c conda-forge -c bioconda --prefix /home/users/bruno.moda/amptk2 amptk r-base python icu=64.2
```
As I understood, the problem was with the version from this **icu** R package. When I create a new env based on the new version (64.2) the problem was solved (I checked by entering R within conda env and load the "stringi" package with library(stringi) and got no error just like the mentioned above).
Right now I'm re-running the dada2 script within amptk to see if this will work. I didn't wait until this step was finished because it takes too long to be completed, and I still don't get it. Just for the record, I'm using 24 cores (~66GB RAM), and the other clustering step got completed much faster than this dada2 step (dada2 took almost 3 days to be completed, just in the split FASTQ files step).

**Comment by nextgenusfs** [comment]
Glad you got it working. Dada2 is slow in comparison to the rest of the tools.

**Comment by nextgenusfs** [comment]
3 days seems a bit long though. How many samples do you have? Basically dada2 requires each sample fastq to be in its own file - this is not how the rest of amptk works so it has to split the demuxed fastq file into sample bins - which requires reading the sample name from the header. I will look at the code, this might be able to be sped up.

**Comment by nextgenusfs** [comment]
Its currently running as fast as it can with the python FASTQ parser.  It reads through the demuxed FASTQ file one-time and splits sequences by their `barcodelabel=` in the FASTQ header.  The function is here: https://github.com/nextgenusfs/amptk/blob/master/amptk/dada2.py#L38-L48

If you can find a faster way to do this without adding more dependencies I'm happy to implement -- I'm not sure if possible with newest version of vsearch -- but that would be the place I would look first.  Tool/function needs to start with single FASTQ file and split into "sample" FASTQ files based on `barcodelabel=`, ie `barcodelabel=sample1` would output into sample1.fastq, etc.

**Comment by bsmoda** [comment]
> 3 days seems a bit long though. How many samples do you have? Basically dada2 requires each sample fastq to be in its own file - this is not how the rest of amptk works so it has to split the demuxed fastq file into sample bins - which requires reading the sample name from the header. I will look at the code, this might be able to be sped up.

I'm doing the analysis of 40 samples from AMPTk Ion PGM data. I download the SRA data and did the demux step with amptk SRA script in a directory with one FASTQ file per sample. The output was one fastq.gz demux file.

**Comment by nextgenusfs** [comment]
Huh... that shouldn't take that long.  But its doing what it should do, ie SRA files are per sample but primers have not been trimmed, so it should relabel headers, trim primers, and combine into a single demux.fq.gz file.  

You can also get the same data in the original format from here: https://osf.io/4xd9r/. There is a juypter notebook of how the data was processed for the paper -- its all contained in the 'amptk_paper' folder.
