### ISSUE TITLE
DADA2 Pseudopooling

### ISSUE THREAD

**Issue by MycoMap** [nextgenusfs/amptk#65]
Could this be included as an option in the script?

https://benjjneb.github.io/dada2/pseudo.html

**Comment by nextgenusfs** [comment]
Shouldn’t be too hard to update the code.  Pooling is already enabled by passing —pool option, which should be more accurate than the new pseudo pooling method.

**Comment by MycoMap** [comment]
The issue is memory. Pseudopooling only requires linear increases so it may work better for large datasets. I cannot finish due to memory constraints, even when using a VM with huge allocations.
