### ISSUE TITLE
Error at Taxonomy step (ASV clustering from DADA2)

### ISSUE THREAD

**Issue by hlfreund** [nextgenusfs/amptk#68]
So I am rerunning my Amptk script and for some reason, I keep getting an error at the consensus OTU table step while using the taxonomy command. I have run Amptk before, with DADA2,  and did not run into this error.

Basically I get UTAX, SINTAX, and global alignment results - but then the consensus step does not occur. I've tried using the script with and without a mapping file (at first I thought that was the issue), but still not having luck.

I have also taken a screenshot of my script and attached it to this post.

Processing\r03:55 565Mb    96.7% Processing\r03:56 565Mb    97.1% Processing\r03:57 565Mb    97.6% Processing\r03:58 565Mb    98.1% Processing\r03:59 565Mb    98.5% Processing\r04:00 565Mb    99.0% Processing\r04:01 565Mb    99.4% Processing\r04:02 565Mb    99.9% Processing\r04:02 565Mb   100.0% Processing\r\n'
[02/21/20 06:05:24]: UTAX results parsed, resulting in 17,063 taxonomy predictions
[02/21/20 06:05:25]: SINTAX results parsed, resulting in 9,531 taxonomy predictions
[02/21/20 06:05:35]: Global alignment results parsed, resulting in 17,258 taxonomy predictions
[ITS1_XCZO_NoMap.cluster.amptk-taxonomy.log](https://github.com/nextgenusfs/amptk/files/4263871/ITS1_XCZO_NoMap.cluster.amptk-taxonomy.log)
<img width="1097" alt="amptk-script-screenshot" src="https://user-images.githubusercontent.com/57795548/75482724-39362580-595a-11ea-9cca-988bd2177533.png">

Thanks for your help!

**Comment by nextgenusfs** [comment]
Huh, strange.  There is this warning from `usearch` about `Max OMP threads 12`.  Did you try setting the --cpus option, ie `--cpus 12`?

**Comment by hlfreund** [comment]
I am running my program via our cluster system and have the following code for cpu calling:
`CPU=1
if [ $SLURM_CPUS_ON_NODE ]; then
CPU=$SLURM_CPUS_ON_NODE
fi
`
So I set the cpu option in the initial preprocessing (demultiplexing) step, and that's it. Do you think it's necessary to call for it again in the taxonomy step? 

<img width="1333" alt="Screen Shot 2020-02-27 at 5 02 53 PM" src="https://user-images.githubusercontent.com/57795548/75500973-6a771b80-5983-11ea-8132-e606f91fb2ba.png">



<img width="1177" alt="Screen Shot 2020-02-27 at 5 05 14 PM" src="https://user-images.githubusercontent.com/57795548/75500957-59c6a580-5983-11ea-9ded-10d299264e59.png">

**Comment by nextgenusfs** [comment]
I'm not sure.  Working through a few things here.  Surprisingly my local taxonomy database just died on me with a similar error -- I don't quite know why yet.  Since UNITE did a new release, I'm going to build new database as well to package in next release.

**Comment by nextgenusfs** [comment]
I'm hoping this is fixed in most recent release, reopen if still an issue.
