### ISSUE TITLE
drop UTAX from taxonomy?

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/amptk#69]
UTAX was dropped in usearch v10 and it is becoming difficult to build the databases with 32 bit free version due to increase in size of database.  Coupled with vsearch 64-bit now also having sintax, wondering if time to retire UTAX from the classifiers.  This change would unpin the usearch9 dependency, ie could use usearch10/11/etc.

**Comment by mjusino** [comment]
Was UTAX dropped? I was just getting ready to ask this question, I still get it coming up in the taxonomy output files for version 1.5.2, but every OTU has "no hit" for utax.

**Comment by nextgenusfs** [comment]
Yeah it is not run by default due to Mac OS and usearch9 causing problems. So hybrid default search uses vsearch global and vsearch sintax. That way usearch is not explicitly required anymore.

**Comment by nextgenusfs** [comment]
And the other reason is that UTAX is incredibly difficult to train when you only have the free 32 but version. So I had to always take shortcuts and limit which data was used for training -- ultimately it was somewhat trial/error/guesswork.
