### ISSUE TITLE
F and R primers not found, seqs not dropped? 

### ISSUE THREAD

**Issue by hlfreund** [nextgenusfs/amptk#71]
Hi everybody!

So I am currently running Amptk with some ITS1 reads, and I noticed this in the errors output file...(see screenshot).

Will this be a problem later? Am I missing something with why this is happening? I called for the primers used in my script, but for some reason it seems to be ignored.

Thank you friends!

<img width="783" alt="Screen Shot 2020-03-06 at 5 56 44 PM" src="https://user-images.githubusercontent.com/57795548/76134596-56ab6500-5fd4-11ea-8169-3567d13fc3b6.png">

My code is below:
`CPU=1
if [ $SLURM_CPUS_ON_NODE ]; then
CPU=$SLURM_CPUS_ON_NODE
fi

hostname
module unload miniconda3
module load miniconda2
module load amptk/1.4.0

BASE=ITS1_XCZO_depth
#using mapping file that includes site+depth but in a later step rather than the first steps

#STEP1 [demultiplexing the fastq file;  amptk illumina processes a folder of demultiplexed paired-end (PE) reads]

if [ ! -f $BASE.demux.fq.gz ]; then
 amptk illumina -i xczo_its1_demultiplexed/ -l 300 -f ITS1-F -r ITS2 --require_primer off -o $BASE -m XCZO_ITS1_MappingFile_Depth.txt --reads forward --merge_method vsearch --usearch usearch9 --cpus $CPU --rescue_forward on --primer_mismatch 2
fi

#STEP2 [using DADA2 to assign ESVs and also make an OTU table]

if [ ! -f $BASE.cluster.otu_table.txt ];  then
 amptk dada2 -i $BASE.demux.fq.gz -o $BASE --platform illumina
fi

#STEP3 [filtered for low-abundance OTUs]

if [ ! -f $BASE.cluster.filtered.otus.fa ]; then
 amptk filter -i $BASE.cluster.otu_table.txt -f $BASE.cluster.otus.fa -p 0.005
fi

#STEP4 [assigning OTUs to taxas; default method in AMPtk is ‘hybrid’ taxonomy assignment

if [ ! -f $BASE.cluster.taxonomy.txt ] || [ ! -f $BASE.cluster.otu_table.taxonomy.txt ]; then
 amptk taxonomy -f $BASE.cluster.filtered.otus.fa -i $BASE.cluster.final.txt -d ITS1
fi

#STEP5 [FunGuild is a tool for assigning functional information to OTUs]

if [ ! -f $BASE.guilds.txt ] || [ ! -f $BASE.cluster.guilds.txt ]; then
 amptk funguild -i $BASE.cluster.otu_table.taxonomy.txt --db fungi -o $BASE
fi

#STEP6 [traverse the taxonomy tree from an OTU table that is appended with taxonomy information, i.e. the output of amptk taxonomy]

if [ ! -f $BASE.summarize.pdf ] || [ ! -f $BASE.cluster.summarize.pdf ]; then
amptk summarize -i $BASE.cluster.otu_table.taxonomy.txt --graphs -o $BASE --format pdf --percent
fi
`

**Comment by nextgenusfs** [comment]
How did you generate your sequencing data? Are the primers still intact, ie you used Illumina default sequencing primers? Or did you use nested custom sequencing primers and the primer sequences are stripped from your data?

**Comment by hlfreund** [comment]
The sequences were sent to Argonne and demultiplexed for us, so I believe they’ve been stripped. Maybe this is why? Sorry that this is just occurring to me now. We also only used forward reads with this analysis. 

Best,

Hannah
