### ISSUE TITLE
How to match "Zotu" to "ASV" when UNOISE3(AMPtk) generates "Zotu" while sequences in $BASE.ASVs.fa were labeled as "ASV" 

### ISSUE THREAD

**Issue by npomb001** [nextgenusfs/amptk#72]
Hi @nextgenusfs 

I am trying to use UNOISE3 in AMPtk and I was able to complete the run successfully.
However, when I checked the output, I am not sure how I can match "Zotu" to "ASV". UNOISE3(in AMPtk) generated otu table and OTU IDs were "Zotu" (Zotu1 - Zotu30946), but the sequences in $.ASVs.fa were generated as "ASV" (ASV1-ASV30514). Anyway, number of lines are exactly the same. Therefore, total number of "Zotu" = total number of "ASVs". My question is How do we match them when their running numbers are not the same? For example, which ASV does Zotu30946 match to? Do we match them using sorted otu table or original otu table?

Is there a way for you to update the pipeline so the labels are consistent across the outputs?
*Note: this is not an issue when using DADA2.

Best,
Nat

**Comment by nextgenusfs** [comment]
Hi @npomb001.  Thanks for reporting -- these seems like a minor bug.  I should be able to fix in next release.
