### ISSUE TITLE
Estimate rate of index hopping consistent with amptk filter

### ISSUE THREAD

**Issue by marissalee** [nextgenusfs/amptk#75]
Hi amptk community, I am interested in estimating the rate of index hopping in my Illumina MiSeq dataset but am having a difficult time installing AMPtk because of this [issue](https://github.com/nextgenusfs/amptk/issues/70). 

I currently use the [dada2 ITS pipeline](https://benjjneb.github.io/dada2/ITS_workflow.html) and am curious if I can adapt the cutAdapt step to estimate the rate of index hopping from my synthetic mock sample into the biological samples in the sequencing run. Do you have any suggestions for how to do this so that it is consistent with the [filtering function in amptk](https://amptk.readthedocs.io/en/latest/filtering.html#filtering)?

I'd appreciate any and all suggestions! Thanks, Marissa

**Comment by nextgenusfs** [comment]
Hi @marissalee.  I think that the current code in master does not require `usearch` -- there maybe some remaining bugs as I haven't had the time to thoroughly test it. But the idea is that all `usearch` steps have been migrated to have equivalent steps in `vsearch`, including taxonomy.  I need to find the time to build/test/release the updated databases for taxonomy - so the default "hybrid" taxonomy might not be functional quite yet, but you can use just `vsearch` for example. 

So probably the easiest way to install the current code in master would be to install v1.4.2 in a conda environment as the instructions indicate:
```
#build environment and install amptk
conda create -n amptk "python>=3" amptk

#activate environment
conda activate amptk

#then install code in master
python -m pip install git+https://github.com/nextgenusfs/amptk.git
```
This will update amptk to the current code in master.  Please open issues if you encounter any problems. But you should then be able to process data without the need for `usearch`

**Comment by marissalee** [comment]
Thank you for the quick response! I will give it a shot.

**Comment by nextgenusfs** [comment]
Hopefully you got this working? Reopen if still a problem.
