### ISSUE TITLE
COI Database build strips specific epithet from species column

### ISSUE THREAD

**Issue by JonathanVanHamme** [nextgenusfs/amptk#81]
Hi Jon,

My student (finally) noticed that the specific epithet is not included for any of her taxonomy assignments from the COI database build I did in November 2020 (issue #77 ). I had a look at:

```
arth-chord.bold-reformated.fasta
```

and the specific epithets are there:

```
cat arth-chord.bold-reformated.fasta | grep '>' | head
>BOLD:AAA8924_KM616161;tax=k:Animalia,p:Arthropoda,c:Collembola,o:Entomobryomorpha,f:Entomobryidae,g:Entomobrya,s:Entomobrya nivalis
>BOLD:AAA8924_KM616780;tax=k:Animalia,p:Arthropoda,c:Collembola,o:Entomobryomorpha,f:Entomobryidae,g:Entomobrya,s:Entomobrya nivalis
>BOLD:AAA8924_KM615626;tax=k:Animalia,p:Arthropoda,c:Collembola,o:Entomobryomorpha,f:Entomobryidae,g:Entomobrya,s:Entomobrya nivalis
...
```

But they get stripped after:

```
#generate global alignment database
amptk database -i arth-chord.bold.reformated.fasta -f LCO1490 -r mlCOIintR --primer_required none \
    --derep_fulllength --format off --primer_mismatch 4 -o COI --min_len 200 --create_db usearch \
    --install
```

and do not show up in 

```
COI.extracted.fa

>BOLD:AAA2803_GU114062;tax=k:Animalia,p:Arthropoda,c:Insecta,o:Trichoptera,f:Limnephilidae,g:Limnephilus,s:Limnephilus
>BOLD:AAA3657_GU114192;tax=k:Animalia,p:Arthropoda,c:Insecta,o:Trichoptera,f:Limnephilidae,g:Limnephilus,s:Limnephilus
>BOLD:AAB4584_GU114164;tax=k:Animalia,p:Arthropoda,c:Insecta,o:Trichoptera,f:Limnephilidae,g:Limnephilus,s:Limnephilus
...

```

like they do in your builds.

Thanks!
Jon

[COIb.log](https://github.com/nextgenusfs/amptk/files/6314295/COIb.log)
[COIb.usearch.log](https://github.com/nextgenusfs/amptk/files/6314305/COIb.usearch.log)

**Comment by nextgenusfs** [comment]
Hi @JonathanVanHamme.  Sorry for the very very very long delay.  I think I found and fixed this bug, if you would be able to try with the upcoming v1.5.4 release and ensure that it is fixed that would be great. I ran into the same thing yesterday trying to upgrade the ITS database.
