### ISSUE TITLE
Problem with TypeError during AMPtk cluster

### ISSUE THREAD

**Issue by haideruni** [nextgenusfs/amptk#97]
Hello,

I am relatively new to this package (and coding in general), I've been using AMPtk to analyze my files for a project I'm currently working on. However, when I reach the AMPtk cluster step, my files encounter a TypeError after the "Validating OTU Orientation" message appears. I'm running a script I made on the command line using all the amptk commands. The TypeError is about comparing a NoneType with an Int using >. I've pasted the error message below. ~ is just my home directory in the file paths and my Python version is 3.8. 
```

Example of next cmd: amptk cluster -i SRR11014838_AMPtk.demux.fq.gz -o out

[04:39:16 AM]: OS: CentOS Linux 7, 80 cores, ~ 198 GB RAM. Python: 3.8.5
[04:39:16 AM]: AMPtk v1.5.4, VSEARCH v2.15.2
[04:39:16 AM]: Loading FASTQ Records
[04:43:40 AM]: 52,055,628 reads (2.9 GB)
[04:43:40 AM]: Quality Filtering, expected errors < 1.0
[04:48:22 AM]: 50,339,961 reads passed
[04:48:22 AM]: De-replication (remove duplicate reads)
[04:50:33 AM]: 27,216,921 reads passed
[04:50:51 AM]: Clustering OTUs (VSEARCH --cluster_smallmem)
[04:51:57 AM]: De novo Chimera detection (VSEARCH --uchime_denovo)
[04:54:08 AM]: 190,903 OTUs
[04:54:08 AM]: Cleaning up padding from OTUs
[04:54:10 AM]: Validating OTU orientation
-------------------------------------------------------
Traceback (most recent call last):
  File "~/.conda/envs/mycondaamptkenv/bin/amptk", line 8, in <module>
    sys.exit(main())
  File "~/.conda/envs/mycondaamptkenv/lib/python3.8/site-packages/amptk/amptk.py", line 784, in main
    mod.main(arguments)
  File "~/.conda/envs/mycondaamptkenv/lib/python3.8/site-packages/amptk/OTU_cluster.py", line 190, in main
    numKept, numDropped = amptklib.validateorientation(tmp, sort_out, uchime_out, passingOTUs)
  File "~/.conda/envs/mycondaamptkenv/lib/python3.8/site-packages/amptk/amptklib.py", line 1450, in validateorientation
    if qCount > tCount:
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

```

It seems that in the validateorientation function in amptklib.py, when it makes the dictionaries from orient-map.txt and orient.uc, there is an OTU in orient-map.txt that is present but it doesn't exist in orient.uc. So when the python script attempts to call/index that OTU's size from orient.uc it comes up as a NoneType value. Leading to the TypeError in qCount > tCount. 

This issue is only present with some of my files. Other files are able to go through all the AMPtk steps to get a Taxonomy file without this error. However, I haven't been able to find a notable difference between the successful files and the files with the Error.

I'm a bit unsure how to proceed from here since I'm not entirely familiar with the importance of the step and if any modifications could influence the downstream products of my AMPtk script.  I was advised to post this issue on GitHub as a result.

I'd appreciate any help or advice!

Thanks,
Haider

**Comment by nextgenusfs** [comment]
I'm not entirely sure what the error is, are you able to make a smaller test dataset where this error is reproducible so I can debug?

**Comment by nextgenusfs** [comment]
Or if this data is public via SRA I can try to download, i see this accession in your demux log, SRR11014838. Just give me the commands you issued so I can repeat.

**Comment by haideruni** [comment]
The data is publicly available, that accession is a single-end read. This error also occurred for my paired-end reads as well.

Here are the commands I ran for the SRR11014838 file. $INPUT is the input file variable and $OUTPUT is the output file variable.
 `amptk SRA -i $INPUT -f LR0R -r LR2R -o "$OUTPUT" --cpus 40 --min_len 80 --require_primer off  --primer_mismatch 2`
  `amptk cluster -i "$OUTPUT".demux.fq.gz -o "$OUTPUT"`
The amptk cluster step is where the error occurs. 

It was also trimmed using trimmomatic under this piece of code before having those amptk commands being run on it, I'm not sure if it makes a difference but I've put the code here. $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar is just the path to the trimmomatic jar.
`java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 $INFILE $OUTFILE.fastq ILLUMINACLIP:TruSeq3-SE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 CROP:300`

**Comment by nextgenusfs** [comment]
Definitely do not trim with trimmomatic. I will try to look at it this weekend.

**Comment by nextgenusfs** [comment]
So this experiment appears to be metagenomic data? -- AMPtk is for amplicons... https://www.ncbi.nlm.nih.gov/sra/?term=SRR11014838

**Comment by haideruni** [comment]
The metagenomic dataset should include amplicon data so it should be okay.  The other files I worked with that are metagenomic were able to provide me with results and a taxonomy file at the end when using AMPtk.  

Is there a reason why trimmomatic shouldn't be used for trimming?

**Comment by nextgenusfs** [comment]
Sounds like you might be confused? AMPtk is for pooled amplicons, ie environmental samples with different barcodes -- so the software is expecting barcode--primer--amplicon--primer--barcode, metagenomics data is derived from random ligation of adapters.  While you could certainly pull out reads that have primer sequences and cluster them -- there really isn't a method for that in AMPtk.  Per trimmomatic, I thought you had amplicon data -- so AMPtk works by first finding for/rev primers, trimming them off, then using expected errors quality trimming to filter data to be clustered into OTUS -- so you do not want to 3' or adapter trim the data before it gets to AMPtk.

**Comment by nextgenusfs** [comment]
I don't know the exact cause of the TypeError in the code -- but I suspect it is because the input data is not what AMPtk is expecting. 

Just googled quickly and saw this comparison of the methods, perhaps that will be helpful.  There is a lot of terminology to become familiar with. https://microbialdarkmatter.org/index.php/blog/2-the-difference-between-metagenomics-and-amplicon-sequencing

Generally metagenomics experiments use different tools, ie something like Kraken (and many many others) aimed at classification of the reads in that experiment. Whereas, amplicon sequencing (metabarcoding) involves amplification of a single region of all the organisms in an environment -- and then we try to process those data and identify which organisms are in that sample.

**Comment by haideruni** [comment]
It's been a year since this issue and I've learned more about bioinformatics and metagenomics, I'll close this issue because the error is very likely due to my usage of incorrect input files. Thank you for your help and for discussing some of the background in metagenomics and amplicons.
