### ISSUE TITLE
Problematic unoise3 implementation with VSEARCH

### ISSUE THREAD

**Issue by markschl** [nextgenusfs/amptk#99]
I noticed that Amptk misses the `--sizein` argument in `vsearch -cluster_unoise` ([code here](https://github.com/nextgenusfs/amptk/blob/94ea653b36249e7eac24fa06a8a037bc16e77a25/amptk/unoise3.py#L121)). This leads to size annotations being incorrect in the output, and consequently the chimera checking will fail because the abundance skew is not known correctly.

```bash
cat << EOF > test.fa
>seq1;size=1000
ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTT
>seq2;size=1000
CAAAAGTACATTTTTACACTCTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAA
>seq1-2;size=1 (artifact derived from seq1, last 2 bases changed)
ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCCC
>chim;size=1 (Chimeric sequence, half seq1 / seq 2)
ATGCGATACGTAATGTGAATTGCAGAATTCAGGTAGGGATACCCGCTGAACTTAA
EOF
```

**USEARCH**:
```bash
usearch -unoise3 test.fa -zotus zotus.fa -minsize 1
cat zotus.fa
```
The artifact and the chimera were correctly recognized, output:
```
>Zotu1
ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTT
>Zotu2
CAAAAGTACATTTTTACACTCTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAA
```

**VSEARCH:**
```bash
vsearch --cluster_unoise test.fa --sizeout --centroids zotus_chim.fa --minsize 1
vsearch --sortbysize zotus_chim.fa --output zotus_sorted.fa
vsearch --uchime3_denovo zotus_sorted.fa --nonchimeras zotus.fa
cat zotus.fa
```
Output (same as USEARCH):
```
>seq1;size=1001
ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTT
>seq2;size=1000
CAAAAGTACATTTTTACACTCTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAA
```
Now try removing the `--sizein` from the `cluster_unoise` call. The chimera will also be returned:
```bash
>seq1;size=2
ATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTT
>chim;size=1
ATGCGATACGTAATGTGAATTGCAGAATTCAGGTAGGGATACCCGCTGAACTTAA
>seq2;size=1
CAAAAGTACATTTTTACACTCTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAA
```

Also note that the VSEARCH implementation uses an intermediate size sorting step, which is based on [this example code](https://github.com/torognes/vsearch/pull/283) from the VSEARCH author. I don't know whether it is possible to have unsorted output from `cluster_unoise`, but just wanted to mention this step.

Another note: USEARCH does the chimera checking directly in the `-unoise3` command, so technically the denovo chimera check done on the USEARCH output may not be required. However I never evaluated whether VSEARCH would still find more chimeras in the USEARCH Z-OTUs output.

**Comment by nextgenusfs** [comment]
Thanks @markschl, would you be able to test latest via install with pip to see if working now as you would expect?

**Comment by markschl** [comment]
Thanks for the quick response. I'm having some problems installing the pip version due to dependency issues, I might try at the weekend :)

**Comment by nextgenusfs** [comment]
From that environment should be able to just do:
```
python -m pip install git+https://github.com/nextgenusfs/amptk.git --upgrade --force --no-deps
```

**Comment by markschl** [comment]
Thanks for the hint, I was able to get it running. The results from a small mock community dataset look good, before there were multiple OTUs for a few species and now there is just one. The Amptk DADA2 pipeline also gives almost the same results.

**Comment by nextgenusfs** [comment]
Great thanks for the help.  I will tag a new release then with these fixes.

**Comment by markschl** [comment]
Great! Although, the 'sortbysize' command from the description here https://github.com/torognes/vsearch/pull/283 is still missing. But as I wrote earlier, I'm not absolutely sure whether this is required or not with the current VSEARCH (whether the UNOISE output is always sorted and whether `uchime3_denovo` really needs sorted input).

**Comment by nextgenusfs** [comment]
Yes it is doing sortbysize only for vsearch unoise3.

**Comment by nextgenusfs** [comment]
Yes it is doing sortbysize only for vsearch unoise3.

**Comment by nextgenusfs** [comment]
Yes it is doing sortbysize only for vsearch unoise3.

**Comment by markschl** [comment]
Sorry if I didn't write it clearly enough... I meant that the code linked above proposes a sorting step *between* the `cluster_unoise` and the `uchime3_denovo` step (in the example code the steps are called `unoise` and `uchime_denovo`, but I assume that they are equivalent). However, after having a closer look I actually think that an extra sorting step is not required. The documentation for `uchime_denovo` and `uchime2_denovo` states that the input sequences are automatically sorted by size, only for `uchime3_denovo` this statement is missing. However, [the code](https://github.com/torognes/vsearch/blob/6a302a18c3067dfc312562f4b4b532c6188e8da8/src/chimera.cc#L1827) and the command output (`Sorting by abundance`) suggest that the input is size-sorted in all three cases.

The sorting step *before* the `cluster_unoise` command should not be necessary, since `derep_fulllength` and `fastx_uniques` already provide sorted output (it's not written in the VSEARCH docs of these commands themselves, but rather in the description of `--output`, `--fastaout` and `--fastqout`, it took me some time to find out...). If the output of the de-replication wasn't size sorted, USEARCH would anyway also stop with an error.

**Comment by nextgenusfs** [comment]
Okay, I did implement the sorting after `fastqx_uniques` or `derep_fulllength` (depending on vsearch version which is here: https://github.com/nextgenusfs/amptk/blob/master/amptk/unoise3.py#L156-L183) -- so probably safest to keep the sorting step in there in case older version of vsearch doesn't have `fastq_uniques` that it is properly sorted before `cluster_unoise`. which is here: https://github.com/nextgenusfs/amptk/blob/master/amptk/unoise3.py#L187-L224

Does this seem appropriate as it currently is?

**Comment by markschl** [comment]
> Does this seem appropriate as it currently is?

Sure, the extra sorting step will not do harm at all...

Regarding the USEARCH approach: since the introduction of `unoise` and `cluster_otus` (UPARSE), `uchime_denovo` [has been deprecated](https://www.drive5.com/usearch/manual10/cmd_uchime_denovo.html)/removed from USEARCH because these commands do chimera removal "on the fly" and the author states that this is more effective. But your approach may not be a problem, since at least my impression (based on rather limited experience) is that the VSEARCH `uchime_denovo` seems less strict (removes less chimeras), so the effect of this additional step may be limited.

**Comment by markschl** [comment]
Thanks a lot for fixing this!
